[tool.isort]
profile = "black"
multi_line_output = 3
skip_glob = [
  "AVR/AVR-2024/*",
  "RVR/Arduino-R4-Controller-Web-Interface/*",
  "RVR/RVR-Movement-Code/*",
] # Exclude submodules

[tool.black]
line-length = 200
# Exclude submodules
extend-exclude = '''
/(
AVR/AVR-2024
  | RVR/Arduino-R4-Controller-Web-Interface
  | RVR/RVR-Movement-Code
)
'''

[tool.autoflake]
recursive = true
in-place = true
remove-all-unused-imports = true
expand-star-imports = true
remove-duplicate-keys = true
remove-unused-variables = true
exclude = [
  "AVR/AVR-2024/*",
  "RVR/Arduino-R4-Controller-Web-Interface/*",
  "RVR/RVR-Movement-Code/*",
] # Ignore submodules
